name: Build

on:
  push:
    branches:
      - master
      - dev
      - hotfix/*
      - release/*
      - feature/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Plugin
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin
